import { Species } from './types';

export const SPECIES: Species[] = [
  {
    id: 'phoenix',
    name: 'Phoenix',
    description: 'A blazing bird of eternal rebirth. Its flames never dim.',
    personality: 'wise, poetic, slightly dramatic, speaks with fiery metaphors',
    asciiArt: [
      '         __          __',
      '        /  \\        /  \\',
      '       / .. \\      / .. \\',
      '      /  /\\  \\    /  /\\  \\',
      '     /  /  \\  \\  /  /  \\  \\',
      '    /  /    \\  \\/  /    \\  \\',
      '   /  /  /\\   \\    /\\   \\  \\',
      '  /  /  /  \\       /  \\   \\  \\',
      ' /__/__/____\\_____/____\\___\\',
      '     \\    \\  |  |  /    /',
      '      \\____\\ |  | /____/',
      '            \\|  |/',
      '             |  |',
      '            _|  |_',
    ].join('\n'),
    color: '#fb923c',
    glowColor: '#f97316',
    rarity: 5,
  },
  {
    id: 'dragon',
    name: 'Dragon',
    description: 'An ancient wyrm of immense power and wisdom.',
    personality: 'proud, protective, speaks formally, sometimes grumpy but caring',
    asciiArt: [
      '              __====-_  _-====__',
      '         _--^^^#####//      \\\\#####^^^--_',
      '      _-^##########// (    ) \\\\##########^-_',
      '    -############//  |\\^^/|  \\\\############-',
      '   /############//   (@::@)   \\\\############\\',
      '  /#############((     \\\\//     ))#############\\',
      ' /###############\\\\    (oo)    //###############\\',
      ' /################\\\\  / VV \\  //################\\',
      '/###################\\\\/      \\\\//###################\\',
      '|#####################\\        /#####################|',
      '\\#####################\\      /#####################/',
      ' \\####################\\    /####################/',
      '  \\###################\\  /###################/',
      '   \\\\#################\\/#################//',
      '    \\\\###############/####################//',
      '     \\\\############/#####################//',
      '      \\\\##########/#####################//',
      '       \\\\#######/######################//',
      '        \\\\####/#######################//',
    ].join('\n'),
    color: '#f87171',
    glowColor: '#ef4444',
    rarity: 4,
  },
  {
    id: 'cat',
    name: 'Neko',
    description: 'A mysterious feline companion with glowing eyes.',
    personality: 'playful, curious, sassy, loves naps, speaks casually',
    asciiArt: [
      '    /\\_/\\',
      '   ( o.o )',
      '    > ^ <',
      '   /|   |\\',
      '  (_|   |_)',
      '    "   "',
    ].join('\n'),
    color: '#fbbf24',
    glowColor: '#f59e0b',
    rarity: 1,
  },
  {
    id: 'wolf',
    name: 'Wolf',
    description: 'A loyal lupine spirit of the wild forests.',
    personality: 'stoic, loyal, observant, speaks in short sentences, protective',
    asciiArt: [
      '              ,     ,',
      '             (\\____/)',
      '              (_oo_)',
      '               (O)',
      '             __||__    \\)',
      '     []/______\\[]      /',
      '     /\\______/ \\    /',
      '    / /_______/ \\  /',
      '    \\/_______/   \\/',
      '',
      '            /\\  /\\',
      '           (  \\/  )',
      '            \\    /',
      '             \\  /',
      '              \\/',
    ].join('\n'),
    color: '#94a3b8',
    glowColor: '#64748b',
    rarity: 2,
  },
  {
    id: 'slime',
    name: 'Slime',
    description: 'A bouncy gelatinous creature. Adorably squishy.',
    personality: 'bubbly, innocent, excitable, speaks with many exclamation marks',
    asciiArt: [
      '      .---.',
      '     / o o \\',
      '    |  \\_/  |',
      '     \\_____/ ',
      '    /|     |\\',
      '   / |     | \\',
      '  |  |_____|  |',
      '  |___________|',
    ].join('\n'),
    color: '#4ade80',
    glowColor: '#22c55e',
    rarity: 1,
  },
  {
    id: 'owl',
    name: 'Owl',
    description: 'A wise nocturnal guardian of ancient knowledge.',
    personality: 'wise, thoughtful, uses big words, gives advice, slightly nerdy',
    asciiArt: [
      '       ___',
      '     /`   `\\',
      '    /  o o  \\',
      '   |   ___   |',
      '    \\  \\_/  /',
      '  ___\\_____/___',
      ' /   /     \\   \\',
      '|   |  ()  |   |',
      ' \\   \\ ___ /   /',
      '  `---|   |---`',
      '      |   |',
      '     _|   |_',
      '    (_______)',
    ].join('\n'),
    color: '#d97706',
    glowColor: '#b45309',
    rarity: 2,
  },
  {
    id: 'unicorn',
    name: 'Unicorn',
    description: 'A majestic creature of pure light and magic.',
    personality: 'graceful, elegant, speaks poetically, dreamy, kind',
    asciiArt: [
      '            *',
      '           / \\',
      '          / _ \\',
      '         / / \\ \\',
      '    ____/ /   \\ \\____',
      '   /     /     \\     \\',
      '  /  o  /  (O)  \\  o  \\',
      ' /_____\\_________/_____\\',
      '  |   \\     |     /   |',
      '  |    \\    |    /    |',
      '  |     \\   |   /     |',
      '   \\     \\__|__/     /',
      '    \\_____/ | \\_____/',
      '          _|_|_',
      '         (_____)',
    ].join('\n'),
    color: '#f0abfc',
    glowColor: '#d946ef',
    rarity: 3,
  },
  {
    id: 'robot',
    name: 'Robot',
    description: 'A friendly mechanical companion from the future.',
    personality: 'logical, helpful, makes beeping sounds, uses data-driven language',
    asciiArt: [
      '     +--------+',
      '     | [==  ==]|',
      '     |   __    |',
      '     |  |__|   |',
      '     +--+--+---+',
      '     /|  |  |  |\\',
      '    / |  |  |  | \\',
      '   |  |__|__|__|  |',
      '   |   ________   |',
      '   |  |  |  |  |  |',
      '   |__|__|__|__|__|',
      '      |__|  |__|',
    ].join('\n'),
    color: '#22d3ee',
    glowColor: '#06b6d4',
    rarity: 3,
  },
  {
    id: 'ghost',
    name: 'Ghost',
    description: 'A playful spectral entity from beyond the veil.',
    personality: 'mysterious, playful, speaks in whispers, makes spooky jokes',
    asciiArt: [
      '    .-.',
      '   (o o)',
      '  /| Y |\\',
      '   |   |',
      '   |___|',
      '    | |',
      '   _| |',
      '  (___|',
      '    | |',
      '   _| |_',
      '  (_____)',
    ].join('\n'),
    color: '#cbd5e1',
    glowColor: '#e2e8f0',
    rarity: 2,
  },
  {
    id: 'turtle',
    name: 'Turtle',
    description: 'An ancient and patient wanderer of the seas.',
    personality: 'slow, patient, wise from experience, speaks calmly, never rushes',
    asciiArt: [
      '        _____',
      '      /       \\',
      '     /  ^   ^  \\',
      '    |  \\___/  |',
      '    |_________|',
      '   /           \\',
      '  / /|       |\\ \\',
      ' / / |       | \\ \\',
      ' \\ \\ |_______| / /',
      '  \\_\\|_______|/_/',
      '     |       |',
      '    _|_     _|_',
      '   (___)   (___)',
    ].join('\n'),
    color: '#34d399',
    glowColor: '#10b981',
    rarity: 1,
  },
  {
    id: 'bunny',
    name: 'Bunny',
    description: 'A fluffy and energetic hopper of the meadows.',
    personality: 'hyperactive, adorable, loves carrots, speaks very fast, giggly',
    asciiArt: [
      '   /\\ /\\',
      '  ( o.o )',
      '  =( >v< )=',
      '   (     )',
      '   /|   |\\',
      '  (_|   |_)',
      '   "   "',
    ].join('\n'),
    color: '#fda4af',
    glowColor: '#fb7185',
    rarity: 1,
  },
  {
    id: 'fox',
    name: 'Fox',
    description: 'A clever and cunning trickster of the wild.',
    personality: 'clever, witty, charming, a bit mischievous, loves riddles',
    asciiArt: [
      '      /\\_/\\',
      '     / @ @ \\',
      '    ( > w < )',
      '    /|  |  |\\',
      '   (_|  |  |_)',
      '     |  |  |',
      '    (__|__|)',
      '',
      '      / \\',
      '     /   \\',
      '    /     \\',
    ].join('\n'),
    color: '#fb923c',
    glowColor: '#ea580c',
    rarity: 2,
  },
];

export function getSpeciesById(id: string): Species | undefined {
  return SPECIES.find((s) => s.id === id);
}
